- name: Redford Cam 
  hosts: localhost
  tasks:

    - name: Add pilight apt source
      apt_repository:
        repo: deb http://apt.pilight.org/ stable main
        state: present
    - name: Add pilight apt key
      apt_key:
        id: F2FB87E2E57085B61137D70ACC28DD82EF4C718C
        url: http://apt.pilight.org/
        state: present
    - name: Install the latest version of apps needed for Pilight to function
      package:
        name:
          - python3
          - git
          - cec-utils
          - pilight
        state: latest
    - name: Stop service pilight, if started
      service:
        name: pilight
        state: stopped
    - name: Template pilight json config to /etc/pilight
      template:
        src: /home/pi/redford-ansible/files/pilight/config.json
        dest: /etc/pilight/config.json
        owner: root
        group: root
        mode: '0755'
    - name: Started service pilight, if stopped
      service:
        name: pilight
        state: started
    - name: RedfordSchedule | Create Unit file
      template: 
        src=/home/pi/redford-ansible/files/services/redfordschedule.service.j2
        dest=/etc/systemd/system/redfordschedule.service
        mode=644
      notify:
        - reload systemctl
    - name: RedfordSchedule | Start RedfordSchedule
      service: 
        name=redfordschedule.service 
        state=started
        enabled=yes