# Installs Redford-Speech docker based SERVER (custom port)
docker.io
- name: Redfordspeech
  hosts: localhost #Should be ran on localhost
  tasks:
    - name: Install the latest version of apps needed for Redfordspeech to function
      package:
        name:
          - docker.io
          - python3
          - python3-pip
     - name: Install docker sdk python package
      pip:
        name: docker
    - name: Start service docker, if stopped
      service:
        name: docker
        state: started
        enabled: yes
    - name: adding existing user 'pi' to group docker
      user:
        name: 'pi'
        groups: docker
        append: yes
    - name: pull redfordspeech docker image
      docker_image:
        name: superrobertwa/redfordspeech
    - name: Start container with startup script
      community.general.docker_container:
        name: redfordserver
        image: superrobertwa/redfordspeech
        command: "./start.sh"
