# Installs Redford-Speech docker based SERVER (custom port)
- name: Redfordspeech
  hosts: localhost #Should be ran on localhost
  tasks:
    - name: Install the latest version of apps needed for Redfordspeech to function
      package:
        name:
          - docker.io
          - python3
          - python3-pip
    - name: Install docker sdk python package
      pip:
        name: docker
    - name: Start service docker, if stopped
      service:
        name: docker
        state: started
        enabled: yes
    - name: adding existing user 'pi' to group docker
      user:
        name: 'pi'
        groups: docker
        append: yes
    - name: add textclient service files
      template: 
        src=/home/surowa/redford-ansible/files/services/redfordtextclient.service.j2
        dest=/etc/systemd/system/redfordtextclient.service
        mode=644
    - name: add service that implemements text client
      service: 
        name=redfordtextclient.service 
        state=started
        enabled=yes
    - name: pull redfordspeech docker image
      docker_image:
        name: superrobertwa/redfordspeech:latest
        source: pull
    - name: Start container with startup script
      docker_container:
        name: redfordserver
        image: superrobertwa/redfordspeech:latest
        command: "./start.sh"
        state: started
        recreate: yes
